# For this to work , make sur:
# 1- sshpass package is installed
# 2- environement vairable ANSIBLE_HOST_KEY_CHECKING is set to False :
# export ANSIBLE_HOST_KEY_CHECKING=False
---
- hosts: node-1
  gather_facts: "no"
  vars:
    public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  tasks:
    - debug:
        msg: "public key is {{ DEFAULT_USER_PUB }}"
    


