# Might need to change the DEFAULT_USER value
# and definetely the DEFAULT_USER_PUB value
---
TZ: 'Cameroon/Douala'
ANSIBLE_USER: ansible
DEFAULT_USER: vagrant
DEFAULT_USER_PUB: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDo58M6kpstm8gbvHUD6KmMLLMxoAjrBi1P5iGusijtt ansible@ansible'
# systemd_dir: /etc/systemd/system
MASTER_IP: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
APT_PACKAGES: [ 'bash', 'curl', 'wget', 'grep', 'git', 'ufw', 'net-tools']
MICROK8S_CHANNEL: '1.22/stable'
DASHBOARD_ENABLED: false
DNS_ENABLED: true
DNS_SERVER: '192.168.8.1'
HELM3_ENABLED: true
HOST_ACCESS_ENABLED: false
HOST_ACCESS_IP: '192.168.8.201'
INGRESS_ENABLED: true
LINKERD_ENABLED: false
METALLB_ENABLED: true
METALLB_IP_RANGE: '192.168.8.200-192.168.8.254'
METRICS_SERVER_ENABLED: true
PORTAINER_ENABLED: false
PROMETHEUS_ENABLED: true
RBAC_ENABLED: false
REGISTRY_ENABLED: true
REGISTRY_SIZED: '20Gi'
STORAGE_ENABLED: true
TRAEFIK_ENABLED: true
